disabled_rules: # rule identifiers to exclude from running
# trailing_whitespace.
  
opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string

  # Find all the available rules by running:
  # swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
  - StyloPay # Please specify your project name.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self


# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: error # implicitly
force_try:
  severity: warning # explicitly

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
   warning: 300
   error: 500
   ignores_function_declarations: true
   ignores_comments: true
   ignores_urls: true

function_body_length:
   warning: 30
   error: 50

function_parameter_count:
   warning: 6
   error: 8

# they can set both implicitly with an array
type_body_length:
   warning: 300 # warning
   error: 500 # error
 
# or they can set both explicitly
file_length:
  warning: 500
  error: 600
  ignore_comment_only_lines: true

cyclomatic_complexity:
   warning: 10
   error: 15

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 60
excluded: iPhone # excluded via string
allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey


reporter: "sonarqube" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)

